max_width = 80

match_arm_blocks = false
match_block_trailing_comma = true
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true

imports_granularity = "Crate"
imports_layout = "Vertical"
